when:
  - event: push
    branch: master

steps:
  - name: build
    image: alpine:latest
    commands:
      - echo "This is the build step"
      - echo "binary-data-123" > executable
      - chmod +x executable
  - name: a-test-step
    image: alpine:latest
    commands:
      - echo "Testing ..."
      - ./executable
      - whoami
      - pwd
      - ls -la
